### ISSUE TITLE
Joseki frontend should be accessible from public URL

### ISSUE THREAD

**Issue by v1r7u** [deepnetworkgmbh/joseki#147]
Should be done after #89

**Comment by yufufi** [comment]
We want to use some kind of ingress controller to expose the service publicly. Also we're going to put the demo service to a separate domain (or a subdomain in `deepnetwork.com`) so that people can play with it. This also requires #89 work for security reasons.

Some concerns with this:
* How are we gonna monitor the incoming traffic and deal with suspicious traffic? (maybe Prometheus/Grafana)
* Should we consider Azure Application Gateway which will come with a lot security/monitoring options out of the box.
